import Ldse

l = Ldse.Ldse()
l.inserir_inicio("A")
l.inserir_inicio("B")
l.inserir_inicio("C")
l.remover_inicio()
l.remover_inicio()
l.remover_inicio()
l.inserir_fim("A")
l.inserir_fim("B")
l.inserir_fim("C")
l.show()
l.remover_fim()
l.show()
l.remover_inicio()
l.show()
l.inserir_inicio("A")
l.inserir_fim("C")
l.inserir_fim("D")
l.inserir_fim("E")
l.show()