t = input('Digite algo e direi o seu tipo primitivo e se é numérico:')
print('Tipo:')
print(type(t))
print('É numérico?')
print(t.isnumeric())
print('É alfabético?')
print(t.isalpha())
print('É alfanumérico?')
print(t.isalnum())